language: node_js

node_js:
  - 8
  - 10

script:
  - yarn run build
  - yarn run lint
  - yarn run format
  - yarn run test:coverage

after_success:
  - npx codecov --file=./coverage/lcov.info

notifications:
  email: false

cache:
  yarn: true
  directories:
    - "node_modules"
