language: node_js

node_js:
  - 10

jobs:
  include:
    - stage: lint
      script: yarn run lint
    - script: yarn run format
    - stage: test
      sctipt: run test:coverage
    - stage: build
      script: yarn run build

after_success:
  - npx codecov --file=./coverage/lcov.info

notifications:
  email: false

cache:
  yarn: true
  directories:
    - "node_modules"
