const SPEEDS = {
  TWO_X: 2.0,
  ONE_POINT_FIVE_X: 1.5,
  ONE_POINT_TOW_FIVE_X: 1.25,
  ONE_X: 1.0,
  ZERO_POINT_SEVEN_FIVE_X: 0.75,
  ZERO_POINT_FIVE_X: 0.5,
}

const SPEEDS_DISPLAY_NAME = new Map([
  [SPEEDS.TWO_X, '2.0x'],
  [SPEEDS.ONE_POINT_FIVE_X, '1.5x'],
  [SPEEDS.ONE_POINT_TOW_FIVE_X, '1.25x'],
  [SPEEDS.ONE_X, '1.0x'],
  [SPEEDS.ZERO_POINT_SEVEN_FIVE_X, '0.75x'],
  [SPEEDS.ZERO_POINT_FIVE_X, '0.5x'],
])

export {SPEEDS, SPEEDS_DISPLAY_NAME}
